# Step 02: AXI-Lite echo register.
# Zynq UltraScale+ PS (M_AXI_HPM0_FPD / "GP0") -> SmartConnect ->
# axi_lite_echo custom IP. Validates the PS-PL AXI-Lite control path.
#
# Prerequisite: the custom IP must already be packaged -
#   make package_step02
# (or: vivado -mode batch -source vivado/step02_axi_lite_echo/package_ip.tcl)
#
# The block design itself (axi_lite_echo_overlay_bd.tcl) was captured via
# File -> Export Block Design as TCL from a one-off interactive session -
# see CLAUDE.md's Vivado CLI-vs-GUI workflow.
#
# Usage:
#   source /opt/Xilinx/2025.1/Vivado/settings64.sh
#   vivado -mode batch -source vivado/step02_axi_lite_echo/build.tcl
#
# Outputs: build/step02_axi_lite_echo/axi_lite_echo_overlay.bit
#          build/step02_axi_lite_echo/axi_lite_echo_overlay.hwh

set script_dir  [file dirname [file normalize [info script]]]
set repo_root   [file normalize [file join $script_dir ../..]]
set build_dir   [file join $repo_root build/step02_axi_lite_echo]
set proj_dir    [file join $build_dir _vivado_project]
set ip_repo_dir [file join $build_dir ip_repo]
set proj_name   axi_lite_echo_overlay
set design_name axi_lite_echo_overlay

if {![file exists [file join $ip_repo_dir component.xml]]} {
    error "No packaged IP found at $ip_repo_dir - run package_ip.tcl first (make package_step02)."
}

file mkdir $build_dir

# Create project
create_project $proj_name $proj_dir -part xck26-sfvc784-2LV-c -force
set_property board_part xilinx.com:kr260_som:part0:1.1 [current_project]

# Register the packaged axi_lite_echo IP so the block design below can
# find kr260intro.local:user:axi_lite_echo:1.0 in the IP catalog.
set_property ip_repo_paths $ip_repo_dir [current_project]
update_ip_catalog

# Block design (generated by Export Block Design as TCL; builds PS + IP,
# validates, and saves internally).
source [file join $script_dir axi_lite_echo_overlay_bd.tcl]

# Generate output products (produces .hwh in hw_handoff/)
generate_target all [get_files ${design_name}.bd]

# HDL wrapper (top-level for synthesis)
set wrapper [make_wrapper -files [get_files ${design_name}.bd] -top]
add_files -norecurse $wrapper
set_property top ${design_name}_wrapper [current_fileset]

# Synthesis
launch_runs synth_1 -jobs 4
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    error "Synthesis failed"
}

# Implementation + bitstream
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    error "Implementation failed"
}

# Copy deliverables to build/
set bit [glob ${proj_dir}/${proj_name}.runs/impl_1/*.bit]
set hwh [glob ${proj_dir}/${proj_name}.gen/sources_1/bd/${design_name}/hw_handoff/${design_name}.hwh]

file copy -force $bit [file join $build_dir ${design_name}.bit]
file copy -force $hwh [file join $build_dir ${design_name}.hwh]

puts ""
puts "=== Build complete ==="
puts "  [file join $build_dir ${design_name}.bit]"
puts "  [file join $build_dir ${design_name}.hwh]"
puts "Copy both files to the KR260 and run sw/step02_axi_lite_echo's driver script"
