# Step 03: DMA loopback.
# Zynq UltraScale+ PS (M_AXI_HPM0_FPD) -> SmartConnect -> AXI DMA control
# (S_AXI_LITE). AXI DMA's M_AXI_MM2S/M_AXI_S2MM -> SmartConnect ->
# S_AXI_HP0_FPD for bulk DDR access. M_AXIS_MM2S wired straight into
# S_AXIS_S2MM - a buffer read out of DDR streams directly back into a
# second DDR buffer with no PL logic in between. Validates the PS-PL
# bulk-transfer path ahead of step 04's compute kernel, which will sit
# on that same stream junction.
#
# Stock Xilinx IP only (Zynq PS + AXI DMA) - no custom IP to package.
#
# The block design itself (dma_loopback_bd.tcl) was captured via
# File -> Export Block Design as TCL from a one-off interactive session -
# see CLAUDE.md's Vivado CLI-vs-GUI workflow.
#
# Usage:
#   source /opt/Xilinx/2025.1/Vivado/settings64.sh
#   vivado -mode batch -source vivado/step03_dma_loopback/build.tcl
#
# Outputs: build/step03_dma_loopback/dma_loopback_overlay.bit
#          build/step03_dma_loopback/dma_loopback_overlay.hwh

set script_dir  [file dirname [file normalize [info script]]]
set repo_root   [file normalize [file join $script_dir ../..]]
set build_dir   [file join $repo_root build/step03_dma_loopback]
set proj_dir    [file join $build_dir _vivado_project]
set proj_name   dma_loopback_overlay
set design_name dma_loopback

file mkdir $build_dir

# Create project
create_project $proj_name $proj_dir -part xck26-sfvc784-2LV-c -force
set_property board_part xilinx.com:kr260_som:part0:1.1 [current_project]

# Block design (generated by Export Block Design as TCL; builds PS + DMA,
# validates, and saves internally).
source [file join $script_dir dma_loopback_bd.tcl]

# Generate output products (produces .hwh in hw_handoff/)
generate_target all [get_files ${design_name}.bd]

# HDL wrapper (top-level for synthesis)
set wrapper [make_wrapper -files [get_files ${design_name}.bd] -top]
add_files -norecurse $wrapper
set_property top ${design_name}_wrapper [current_fileset]

# Synthesis
launch_runs synth_1 -jobs 4
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    error "Synthesis failed"
}

# Implementation + bitstream
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    error "Implementation failed"
}

# Copy deliverables to build/
set bit [glob ${proj_dir}/${proj_name}.runs/impl_1/*.bit]
set hwh [glob ${proj_dir}/${proj_name}.gen/sources_1/bd/${design_name}/hw_handoff/${design_name}.hwh]

file copy -force $bit [file join $build_dir ${design_name}.bit]
file copy -force $hwh [file join $build_dir ${design_name}.hwh]

puts ""
puts "=== Build complete ==="
puts "  [file join $build_dir ${design_name}.bit]"
puts "  [file join $build_dir ${design_name}.hwh]"
puts "Copy both files to the KR260 and run sw/step03_dma_loopback's driver script"
